sudo: required

services:
  - docker

before_install:
  - docker build -t jayjung/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jayjung/react-test npm test -- --coverage

after_success:
  - docker build -t jayjung/react-client ./client
  - docker build -t jayjung/react-nginx ./nginx
  - docker build -t jayjung/react-server ./server
  - docker build -t jayjung/react-worker ./worker
  # Login to the docker CLI.
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  # Take those images and push them to docker hub.
  - docker push jayjung/react-client
  - docker push jayjung/react-nginx
  - docker push jayjung/react-server
  - docker push jayjung/react-worker

notifications:
    slack: ezion:slaF5otKZzNu144OzCiT2126
